// Generated by build.py - do not edit by hand.
// Rebuild with:  python3 build.py --notes notes
// notes: 12   links: 22   generated: 2026-09-23 09:01:04
const GRAPH = {
  "nodes": [
    {
      "id": 0,
      "index": 0,
      "label": "First Week in Ayodhya",
      "group": "home",
      "excerpt": "First Week In Ayodhya Day 1: arrive, unlock, air the flat, buy the survival list (see Things To Buy After Moving), and eat out because the kitchen is still in boxes. Day 2: get the water connection running, test the taps, and chase the landlord's plumber about the bathroom leak. Day 3: internet installation slot - I have blocked the whole morning for it (see Internet And Electricity In Ayodhya). Day 4: visit the RML hospital to open a file for Papa's follow-ups and ask about the physiotherapy schedule. Day 5: unpack the study and set the desk up against the window. First full working day from the new flat. Day 6: explore the market for the almirah and the geyser, note prices, do not buy…",
      "path": "home/first-week-in-ayodhya.md",
      "words": 155,
      "chars": 873,
      "degree": 6,
      "wikilinks": [
        "Things To Buy After Moving",
        "Internet And Electricity In Ayodhya",
        "Farewell In Ambala",
        "Budget For The Move"
      ],
      "mentions": [
        "Internet and Electricity in Ayodhya",
        "Budget for the Move",
        "Things to Buy After Moving",
        "Farewell in Ambala"
      ]
    },
    {
      "id": 1,
      "index": 1,
      "label": "Internet and Electricity in Ayodhya",
      "group": "home",
      "excerpt": "Internet And Electricity In Ayodhya Internet: the flat has no existing fibre line, so I have to book a new connection. Two operators service the lane - a Jio fibre reseller and an Airtel authorised guy who quoted 4,999 for installation with 100 Mbps and no monthly for three months. The Jio reseller quoted 3,500 with a 30 Mbps plan. I want the 100 Mbps because I take client calls all day and my phone hotspot is not going to survive a 90 minute call with the screen share on. Electricity: UPPCL connection is already live, meter is in the landlord's name, so I will pay him the bill each month against the reading. I am photographing the meter on the day we move in and will do it again on the…",
      "path": "home/internet-and-electricity-in-ayodhya.md",
      "words": 194,
      "chars": 1017,
      "degree": 3,
      "wikilinks": [
        "Moving Day Checklist"
      ],
      "mentions": [
        "Moving Day Checklist"
      ]
    },
    {
      "id": 2,
      "index": 2,
      "label": "New Flat in Ayodhya",
      "group": "home",
      "excerpt": "New Flat In Ayodhya The flat we want: 2BHK, second floor, near the Devangana crossing, 9,500 a month with a 20,000 deposit. Landlord is a retired teacher who wants a one-year agreement and does not want families with pets - we have no pets so this is fine. What sold me: a proper balcony, the water tank on the roof (no dependence on the municipal line in summer), and the fact that the RML hospital is a 12 minute auto ride. The kitchen is small but has a window, which the other flat did not. Problems: the flat needs a geyser and the wiring is old, so I have budgeted for a stabiliser. The bathroom tap leaks and the landlord says the plumber will come in the first week. I want that in the…",
      "path": "home/new-flat-in-ayodhya.md",
      "words": 172,
      "chars": 909,
      "degree": 2,
      "wikilinks": [
        "Budget For The Move",
        "First Week In Ayodhya"
      ],
      "mentions": [
        "First Week in Ayodhya",
        "Budget for the Move"
      ]
    },
    {
      "id": 3,
      "index": 3,
      "label": "Budget for the Move",
      "group": "money",
      "excerpt": "Budget For The Move Numbers I am working with: Movers, Ambala to Ayodhya by road, 900 km: 26,000 including insurance for the TV and the fridge. Vande Bharat tickets for three: 4,200. New flat deposit: 20,000. First month rent: 9,500. Geyser, stabiliser and a small almirah: 12,000. Miscellaneous and tips: 3,000. That lands at about 74,700 which is above the 55,000 I first told everyone, so the sofa and dining table go on OLX and whatever they bring in comes off this number. Deposit from the old Ambala flat should return 14,000 within a month of handing over the keys, which I am not counting as income until it lands. Rule for the next two months: no new furniture beyond the almirah, no new…",
      "path": "money/budget-for-the-move.md",
      "words": 150,
      "chars": 851,
      "degree": 7,
      "wikilinks": [
        "Things To Buy After Moving"
      ],
      "mentions": [
        "Things to Buy After Moving"
      ]
    },
    {
      "id": 4,
      "index": 4,
      "label": "Things to Buy After Moving",
      "group": "money",
      "excerpt": "Things To Buy After Moving Priority one, first 48 hours: a bucket and a mug, two bed sheets, an extension board, a mat for the kitchen, and a working bulb for the bathroom. This is the survival list and it comes out of the 12,000 I set aside in the Budget For The Move. Priority two, first month: a geyser for the winter bathroom, a small almirah because the flat has no built-in storage, and a water filter - the landlord says the tank water is fine but I am not drinking it unfiltered for a year. Nice to have, deliberately deferred: a second fan, a bookshelf, and a proper study chair. I have put these on a wishlist and will buy them one per month instead of all at once. Where to buy: the main…",
      "path": "money/things-to-buy-after-moving.md",
      "words": 185,
      "chars": 964,
      "degree": 2,
      "wikilinks": [
        "Budget For The Move"
      ],
      "mentions": [
        "Budget for the Move"
      ]
    },
    {
      "id": 5,
      "index": 5,
      "label": "Farewell in Ambala",
      "group": "people",
      "excerpt": "Farewell In Ambala The going-away dinner happens on the 27th at home, and I have been told very firmly that it is not a buffet - Mom is cooking for 22 people. List is basically the neighbours from both floors, my three cousins from Chandigarh side, and Sharmaji who will talk about the traffic the whole evening. Things to do before everyone arrives: return the two books I borrowed from Anita aunty, give back the drill from the landlord (his, not ours), and settle the milkman for the whole month since he refuses to take part payments. Gifts we are carrying for the Ayodhya relatives: two boxes of Ambala sweets, the bedsheet set from the last wedding that we never used, and the photo album of…",
      "path": "people/farewell-in-ambala.md",
      "words": 177,
      "chars": 987,
      "degree": 3,
      "wikilinks": [
        "Internet And Electricity In Ayodhya"
      ],
      "mentions": [
        "Internet and Electricity in Ayodhya"
      ]
    },
    {
      "id": 6,
      "index": 6,
      "label": "Relatives in Ayodhya",
      "group": "people",
      "excerpt": "Relatives In Ayodhya Mama and Mausaji are in the house behind the temple road, which is a 15 minute auto from the new flat - close enough to help, far enough to keep our own routine. Mausaji has already promised to handle the landlord conversation if anything gets sticky, since he knows half the mohalla. Cousin Renu is a nurse at the RML hospital and she is the reason I am not too worried about Papa's follow-ups. She has offered to get us the physiotherapy slot list and says the morning OPD is the one to aim for. People to call once we land: Mausaji (already told him the 30th), Renu about the hospital file, and Chachi who will otherwise hear about the move from someone else and be upset for…",
      "path": "people/relatives-in-ayodhya.md",
      "words": 187,
      "chars": 1000,
      "degree": 2,
      "wikilinks": [
        "Farewell In Ambala",
        "First Week In Ayodhya"
      ],
      "mentions": [
        "First Week in Ayodhya",
        "Farewell in Ambala"
      ]
    },
    {
      "id": 7,
      "index": 7,
      "label": "Moving Day Checklist",
      "group": "prep",
      "excerpt": "Moving Day Checklist Night before: charge the power bank, print the train ticket twice, freeze two water bottles, and put the documents folder in the backpack. Keep 3,000 cash in small notes for the porter and the auto. The morning itself, in order: Movers arrive 6:00 am, load the marked boxes first, furniture last. Photograph every room empty, and every box sealed, for the damage claim. Meter readings for electricity and water - photograph the meters. Hand the keys to the landlord only after the deposit conversation is closed in writing. Leave by 5:10 am for the station for the Booking Train to Ayodhya (movers went a day earlier on the road truck). Do not forget: the gas cylinder return…",
      "path": "prep/moving-day-checklist.md",
      "words": 171,
      "chars": 987,
      "degree": 5,
      "wikilinks": [
        "Booking Train to Ayodhya",
        "Budget For The Move"
      ],
      "mentions": [
        "Budget for the Move",
        "Booking Train to Ayodhya"
      ]
    },
    {
      "id": 8,
      "index": 8,
      "label": "Packing Stuff",
      "group": "prep",
      "excerpt": "Packing Stuff Rule we are sticking to: pack by room, label every box with a number and a room, and keep one \"open first\" box that does not go into the truck. Phase 1 - things we will not need until after we land: winter clothes, extra utensils, the second set of bedsheets, all the photo albums. Phase 2 - kitchen and study. Phase 3 - daily use, medicines and documents, which travel with us in the Booking Train to Ayodhya cabin bag. Boxes so far: 6 large, 9 medium, 4 small. Bubble wrap is doing most of the work. The pressure cooker and the mixer are going in their original cartons with towels stuffed around them. Things we are NOT taking: the old sofa (listing it on OLX), the dining table…",
      "path": "prep/packing-stuff.md",
      "words": 188,
      "chars": 1058,
      "degree": 4,
      "wikilinks": [
        "Booking Train to Ayodhya",
        "Budget For The Move",
        "Moving Day Checklist"
      ],
      "mentions": [
        "Budget for the Move",
        "Moving Day Checklist",
        "Booking Train to Ayodhya"
      ]
    },
    {
      "id": 9,
      "index": 9,
      "label": "Booking Train to Ayodhya",
      "group": "travel",
      "excerpt": "Booking Train to Ayodhya Booked the Vande Bharat from Ambala to Ayodhya via Delhi for the 30th, chair car, window pair on the left side. Booking notes in case I have to do this again: Tatkal opens at 10:00 the previous day and the 3AC fills last, so if the chair car is gone I take 3AC and stop worrying. Two large suitcases, one cabin bag and my laptop sleeve - that is the entire allowance we are using. Timings that matter: leave home by 5:10 am for the Ambala Cantt drop, breakfast at the Delhi halt is a 40 minute window so we carry parathas instead of buying, and we land in Ayodhya by late afternoon. Total door-to-door is about 12 hours. What I want to remember for next time: book chair car…",
      "path": "travel/booking-train-to-ayodhya.md",
      "words": 216,
      "chars": 1154,
      "degree": 4,
      "wikilinks": [
        "Moving To Ayodhya",
        "Packing Stuff",
        "Route And Halts"
      ],
      "mentions": [
        "Packing Stuff",
        "Moving to Ayodhya",
        "Route and Halts"
      ]
    },
    {
      "id": 10,
      "index": 10,
      "label": "Moving to Ayodhya",
      "group": "travel",
      "excerpt": "Moving To Ayodhya We finally decided: the shift to Ayodhya is happening the first week of next month. Mom's been saying it for two years and this time the paperwork actually moved. Why Ayodhya: Papa's knee surgery follow-ups are at the Ram Manohar Lohia hospital, and my new role is remote so I can work from anywhere as long as the internet holds up. Rent here in Ambala has crept up to 14,000 for a place we have outgrown anyway. Plan so far: pack up in three phases (see Packing Stuff), hand over the keys on the 30th, and take the Booking Train to Ayodhya up with the two big suitcases while the movers take everything else by road. The Budget For The Move is roughly 55,000 including the mover…",
      "path": "travel/moving-to-ayodhya.md",
      "words": 173,
      "chars": 968,
      "degree": 4,
      "wikilinks": [
        "Packing Stuff",
        "Booking Train to Ayodhya",
        "Budget For The Move",
        "Moving Day Checklist"
      ],
      "mentions": [
        "Budget for the Move",
        "Moving Day Checklist",
        "Packing Stuff",
        "Booking Train to Ayodhya"
      ]
    },
    {
      "id": 11,
      "index": 11,
      "label": "Route and Halts",
      "group": "travel",
      "excerpt": "Route And Halts Three ways to get from Ambala to Ayodhya and why we picked the train: Road, the full 900 km in one go: cheapest on paper but the mover does this anyway with our boxes, so we would be doing it twice. Ambala to Lucknow by train, halt, then Lucknow to Ayodhya the next morning: two hotel nights, and honestly too much luggage handling. Ambala to Delhi, change, Delhi to Ayodhya on the Booking Train to Ayodhya: one change, one long leg, arrives the same evening. The halt we did consider: a night in Delhi with my cousin so we could drop the heavy bags and travel light the next morning. Decided against it because Papa's medicines need a clean fridge space and we cannot carry insulin…",
      "path": "travel/route-and-halts.md",
      "words": 169,
      "chars": 942,
      "degree": 2,
      "wikilinks": [
        "Booking Train to Ayodhya",
        "Budget For The Move"
      ],
      "mentions": [
        "Budget for the Move",
        "Booking Train to Ayodhya"
      ]
    }
  ],
  "links": [
    {
      "source": 0,
      "target": 1,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 0,
      "target": 2,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 0,
      "target": 3,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 0,
      "target": 4,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 0,
      "target": 5,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 0,
      "target": 6,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 1,
      "target": 5,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 1,
      "target": 7,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 2,
      "target": 3,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 3,
      "target": 4,
      "kind": "wikilink",
      "weight": 6
    },
    {
      "source": 3,
      "target": 7,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 3,
      "target": 8,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 3,
      "target": 10,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 3,
      "target": 11,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 5,
      "target": 6,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 7,
      "target": 8,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 7,
      "target": 9,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 7,
      "target": 10,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 8,
      "target": 9,
      "kind": "wikilink",
      "weight": 6
    },
    {
      "source": 8,
      "target": 10,
      "kind": "wikilink",
      "weight": 3
    },
    {
      "source": 9,
      "target": 10,
      "kind": "wikilink",
      "weight": 6
    },
    {
      "source": 9,
      "target": 11,
      "kind": "wikilink",
      "weight": 6
    }
  ]
};


// `const GRAPH` is the source of truth; the window assignment is a safety net
// for environments that only look at globals.
if (typeof window !== "undefined") window.GRAPH = GRAPH;
