#!/usr/bin/env python3
"""
tools/vendor.py - keep a local copy of the two CDN files, for networks that cannot
reach a CDN at all.

The viewer loads 3d-force-graph (and its three.js) from jsDelivr, falling back to
unpkg and then to ./vendor/. Run this once and the galaxy works with no CDN access:

    python3 tools/vendor.py

It downloads from the npm registry (registry.npmjs.org) rather than from jsDelivr,
because a network that blocks CDNs very often still allows npm. Stdlib only.

Files land in viewer/vendor/ and are deliberately git-ignored: they are third-party
build artefacts, not source. Delete the folder to go back to pure CDN loading.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import sys
import tarfile
import time
import urllib.error
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
VENDOR = os.path.join(ROOT, "viewer", "vendor")

PACKAGES = [
    {
        "name": "three",
        "version": "0.183.0",
        "want": {
            "package/build/three.module.min.js": "three.module.min.js",
            "package/build/three.core.min.js": "three.core.min.js",
        },
        "why": "the exact revision the 3d-force-graph bundle is built against",
    },
    {
        "name": "3d-force-graph",
        "version": "1.80.0",
        "want": {
            "package/dist/3d-force-graph.min.js": "3d-force-graph.min.js",
        },
        "why": "the graph engine itself",
    },
]

REGISTRY = "https://registry.npmjs.org"


def fetch(url: str, timeout: int = 60) -> bytes:
    print("  GET %s" % url)
    req = urllib.request.Request(url, headers={"User-Agent": "alfred-vendor/1.0"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return resp.read()


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Vendor the CDN files into viewer/vendor/")
    ap.add_argument("--force", action="store_true", help="re-download even if the files exist")
    ap.add_argument("--registry", default=REGISTRY)
    args = ap.parse_args(argv)

    os.makedirs(VENDOR, exist_ok=True)
    print("vendoring into %s" % VENDOR)

    manifest = {
        "_comment": "Local fallback copies of the CDN files the viewer uses. "
                    "Generated by tools/vendor.py - git-ignored, safe to delete.",
        "generated": time.strftime("%Y-%m-%d %H:%M:%S"),
        "registry": args.registry,
        "files": {},
    }

    for pkg in PACKAGES:
        name, version = pkg["name"], pkg["version"]
        if not args.force and all(os.path.exists(os.path.join(VENDOR, dest))
                                  for dest in pkg["want"].values()):
            print("  %s@%s already vendored (use --force to refresh)" % (name, version))
            for src, dest in pkg["want"].items():
                with open(os.path.join(VENDOR, dest), "rb") as fh:
                    manifest["files"][dest] = {
                        "package": "%s@%s" % (name, version),
                        "source": "%s/%s/-/%s-%s.tgz" % (args.registry, name, name, version),
                        "sha256": sha256(fh.read()),
                    }
            continue

        url = "%s/%s/-/%s-%s.tgz" % (args.registry, name, name, version)
        try:
            blob = fetch(url)
        except urllib.error.HTTPError as err:
            print("  ! %s@%s: HTTP %s for %s" % (name, version, err.code, url), file=sys.stderr)
            return 1
        except (urllib.error.URLError, OSError) as err:
            print("  ! could not download %s: %s" % (url, err), file=sys.stderr)
            print("    (the npm registry must be reachable from this machine)", file=sys.stderr)
            return 1

        print("    %.1f MB tarball" % (len(blob) / 1048576.0))
        try:
            tar = tarfile.open(fileobj=io.BytesIO(blob), mode="r:gz")
        except tarfile.TarError as err:
            print("  ! %s is not a readable tarball: %s" % (url, err), file=sys.stderr)
            return 1

        with tar:
            for src, dest in pkg["want"].items():
                try:
                    member = tar.getmember(src)
                except KeyError:
                    print("  ! %s is not inside %s" % (src, url), file=sys.stderr)
                    return 1
                data = tar.extractfile(member).read()
                out_path = os.path.join(VENDOR, dest)
                with open(out_path, "wb") as fh:
                    fh.write(data)
                manifest["files"][dest] = {
                    "package": "%s@%s" % (name, version),
                    "from": src,
                    "source": url,
                    "sha256": sha256(data),
                    "bytes": len(data),
                    "why": pkg["why"],
                }
                print("    wrote %-34s %8.1f KB  sha256 %s" % (dest, len(data) / 1024.0, sha256(data)[:16] + "…"))

    with open(os.path.join(VENDOR, "manifest.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)
        fh.write("\n")

    total = sum(f.get("bytes", 0) for f in manifest["files"].values())
    print("\nvendored %d files, %.1f MB total, for %s"
          % (len(manifest["files"]), total / 1048576.0, ", ".join(
              sorted({f["package"] for f in manifest["files"].values()}))))
    print("manifest: %s" % os.path.join(VENDOR, "manifest.json"))
    print("\nThe viewer prefers the CDN and only falls back to viewer/vendor/, so this")
    print("is invisible unless a CDN is unreachable. Restart server.py to pick it up.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
